// BundledPackages.swift — GENERATED, do not edit by hand.
//
// The bundled Python package set is fixed per app build (it ships
// inside the .ipa), so the Packages tab reads this baked-in list
// instead of booting Python + importlib.metadata at runtime. That
// Python introspection took 2-5 s and janked the tab; this is instant.
//
// Regenerate from the built app's python-metadata/*.dist-info after
// changing the python-ios-lib pin (see scripts/gen-bundled-packages).

import Foundation

enum BundledPackages {
    /// 132 packages bundled at build time.
    static let all: [PackageInfo] = [
        PackageInfo(name: "accelerate", version: "0.30.1", summary: "Accelerate", location: nil, category: "ML / AI"),
        PackageInfo(name: "altair", version: "6.0.0", summary: "Vega-Altair: A declarative statistical visualization library for Python.", location: nil, category: "Plotting"),
        PackageInfo(name: "attr", version: "0.3.2", summary: "Simple decorator to set attributes of target function or class in a DRY way.", location: nil, category: "Data"),
        PackageInfo(name: "attrs", version: "24.2.0", summary: "Classes Without Boilerplate", location: nil, category: "Data"),
        PackageInfo(name: "audioop-lts", version: "0.2.1", summary: "audioop module from the Python standard library — backport", location: nil, category: "Media"),
        PackageInfo(name: "av", version: "17.0.1", summary: "PyAV — Python bindings for FFmpeg", location: nil, category: "Media"),
        PackageInfo(name: "beautifulsoup4", version: "4.14.3", summary: "Screen-scraping library", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "blinker", version: "1.9.0", summary: "Fast, simple object-to-object and broadcast signaling", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "Bottleneck", version: "1.6.0", summary: "Fast NumPy array functions written in C", location: nil, category: "Scientific"),
        PackageInfo(name: "bs4", version: "0.0.2", summary: "Dummy package for Beautiful Soup (beautifulsoup4)", location: nil, category: "Utility"),
        PackageInfo(name: "cachetools", version: "6.2.6", summary: "Extensible memoizing collections and decorators", location: nil, category: "Utility"),
        PackageInfo(name: "cairocffi", version: "1.7.1", summary: "cffi-based cairo bindings for Python", location: nil, category: "Utility"),
        PackageInfo(name: "CairoSVG", version: "2.8.2", summary: "A Simple SVG Converter based on Cairo", location: nil, category: "Utility"),
        PackageInfo(name: "Cartopy", version: "0.23.0", summary: "A cartographic Python library with Matplotlib support for visualisation (iOS arm64 cross-compiled)", location: nil, category: "Geo"),
        PackageInfo(name: "certifi", version: "2026.2.25", summary: "Python package for providing Mozilla's CA Bundle.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "cffi", version: "1.17.1", summary: "Foreign Function Interface for Python calling C code", location: nil, category: "Utility"),
        PackageInfo(name: "charset-normalizer", version: "3.4.7", summary: "The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "ciso8601", version: "2.3.3", summary: "Fast ISO8601 date time parser for Python written in C", location: nil, category: "Performance"),
        PackageInfo(name: "click", version: "8.1.7", summary: "Composable command line interface toolkit", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "cloup", version: "3.0.5", summary: "Adds features to Click: option groups, constraints, subcommand sections and help themes.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "cssselect2", version: "0.8.0", summary: "CSS selectors for Python ElementTree", location: nil, category: "Utility"),
        PackageInfo(name: "cycler", version: "0.12.1", summary: "Composable style cycles", location: nil, category: "Plotting"),
        PackageInfo(name: "dash", version: "4.1.0", summary: "A Python framework for building reactive web-apps. Developed by Plotly.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "decorator", version: "5.3.1", summary: "Decorators for Humans", location: nil, category: "Utility"),
        PackageInfo(name: "dill", version: "0.4.1", summary: "serialize all of Python", location: nil, category: "Utility"),
        PackageInfo(name: "filelock", version: "3.28.0", summary: "A platform independent file lock.", location: nil, category: "Data"),
        PackageInfo(name: "Flask", version: "3.1.3", summary: "A simple framework for building complex web applications.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "flexcache", version: "0.3", summary: "Saves and loads to the cache a transformed versions of a source object.", location: nil, category: "Utility"),
        PackageInfo(name: "flexparser", version: "0.4", summary: "Parsing made fun ... using typing.", location: nil, category: "Utility"),
        PackageInfo(name: "fsspec", version: "2026.3.0", summary: "File-system specification", location: nil, category: "Data"),
        PackageInfo(name: "ftfy", version: "6.3.1", summary: "Fixes mojibake and other problems with Unicode, after the fact", location: nil, category: "Utility"),
        PackageInfo(name: "gitdb", version: "4.0.12", summary: "Git Object Database", location: nil, category: "Utility"),
        PackageInfo(name: "GitPython", version: "3.1.50", summary: "GitPython is a Python library used to interact with Git repositories", location: nil, category: "Utility"),
        PackageInfo(name: "h11", version: "0.16.0", summary: "A pure-Python, bring-your-own-I/O implementation of HTTP/1.1", location: nil, category: "Utility"),
        PackageInfo(name: "httpcore", version: "1.0.9", summary: "A minimal low-level HTTP client.", location: nil, category: "Utility"),
        PackageInfo(name: "huggingface-hub", version: "0.24.7", summary: "Client library to download and publish models, datasets and other repos on the huggingface.co hub", location: nil, category: "ML / AI"),
        PackageInfo(name: "idna", version: "3.11", summary: "Internationalized Domain Names in Applications (IDNA)", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "importlib_metadata", version: "8.7.1", summary: "Read metadata from Python packages", location: nil, category: "Utility"),
        PackageInfo(name: "isort", version: "6.1.0", summary: "A Python utility / library to sort Python imports.", location: nil, category: "Utility"),
        PackageInfo(name: "isosurfaces", version: "0.1.2", summary: "Construct isolines/isosurfaces over a 2D/3D scalar field defined by a function (not a uniform grid)", location: nil, category: "Animation"),
        PackageInfo(name: "itsdangerous", version: "2.2.0", summary: "Safely pass data to untrusted environments and back.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "Jinja2", version: "3.1.6", summary: "A very fast and expressive template engine.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "jsonschema", version: "4.26.0", summary: "An implementation of JSON Schema validation for Python", location: nil, category: "Data"),
        PackageInfo(name: "jsonschema-specifications", version: "2024.10.1", summary: "JSON Schema meta-schemas and vocabularies", location: nil, category: "Data"),
        PackageInfo(name: "Levenshtein", version: "0.27.3", summary: "Python extension for computing string edit distances and similarities.", location: nil, category: "Performance"),
        PackageInfo(name: "manim", version: "0.19.0", summary: "Animation engine for explanatory math videos.", location: nil, category: "Animation"),
        PackageInfo(name: "manimpango", version: "0.6.1", summary: "Bindings for Pango (text layout) for use by manim", location: nil, category: "Animation"),
        PackageInfo(name: "mapbox-earcut", version: "1.0.3", summary: "Python bindings for the mapbox/earcut polygon-triangulation library", location: nil, category: "Animation"),
        PackageInfo(name: "markdown-it-py", version: "3.0.0", summary: "Python port of markdown-it. Markdown parsing, done right!", location: nil, category: "Utility"),
        PackageInfo(name: "MarkupSafe", version: "3.0.3", summary: "Safely add untrusted strings to HTML/XML markup.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "matplotlib", version: "3.9.0", summary: "Python plotting package", location: nil, category: "Plotting"),
        PackageInfo(name: "mdurl", version: "0.1.2", summary: "Markdown URL utilities", location: nil, category: "Utility"),
        PackageInfo(name: "moderngl", version: "5.12.0", summary: "ModernGL: High performance rendering for Python 3", location: nil, category: "Animation"),
        PackageInfo(name: "moderngl-window", version: "2.4.6", summary: "A cross-platform helper library for ModernGL / GLFW / SDL2 windows", location: nil, category: "Animation"),
        PackageInfo(name: "mpmath", version: "1.4.1", summary: "Python library for arbitrary-precision floating-point arithmetic", location: nil, category: "Scientific"),
        PackageInfo(name: "narwhals", version: "1.16.0", summary: "Extremely lightweight compatibility layer between dataframe libraries", location: nil, category: "Plotting"),
        PackageInfo(name: "networkx", version: "3.6.1", summary: "Python package for creating and manipulating graphs and networks", location: nil, category: "Scientific"),
        PackageInfo(name: "numexpr", version: "2.14.1", summary: "Fast numerical expression evaluator for NumPy", location: nil, category: "Scientific"),
        PackageInfo(name: "numpy", version: "2.3.5.post1", summary: "Fundamental package for array computing in Python", location: nil, category: "Scientific"),
        PackageInfo(name: "offlinai-ai", version: "0.1.0", summary: "OfflinAi local AI bridge — model loader / generator", location: nil, category: "Utility"),
        PackageInfo(name: "offlinai-latex", version: "1.0.1", summary: "OfflinAi LaTeX bridge — Busytex driver for manim/MathTex", location: nil, category: "Utility"),
        PackageInfo(name: "offlinai-shell", version: "0.1.0", summary: "OfflinAi interactive shell", location: nil, category: "Utility"),
        PackageInfo(name: "orjson", version: "3.11.9", summary: "Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy", location: nil, category: "Performance"),
        PackageInfo(name: "packaging", version: "26.0", summary: "Core utilities for Python packages", location: nil, category: "Utility"),
        PackageInfo(name: "pandas", version: "2.2.3", summary: "Powerful data structures for data analysis, time series, and statistics", location: nil, category: "Utility"),
        PackageInfo(name: "patsy", version: "1.0.2", summary: "A Python package for describing statistical models and for building design matrices.", location: nil, category: "Utility"),
        PackageInfo(name: "peft", version: "0.12.0", summary: "Parameter-Efficient Fine-Tuning (PEFT)", location: nil, category: "ML / AI"),
        PackageInfo(name: "periodictable", version: "2.1.0", summary: "Extensible periodic table of the elements", location: nil, category: "Utility"),
        PackageInfo(name: "pillow", version: "11.0.0", summary: "Python Imaging Library (Fork)", location: nil, category: "Media"),
        PackageInfo(name: "Pint", version: "0.25.3", summary: "Physical quantities module", location: nil, category: "Utility"),
        PackageInfo(name: "pip", version: "26.0.1", summary: "The PyPA recommended tool for installing Python packages.", location: nil, category: "Utility"),
        PackageInfo(name: "plotext", version: "5.3.2", summary: "plotext plots directly on terminal", location: nil, category: "Utility"),
        PackageInfo(name: "plotly", version: "6.6.0", summary: "An open-source interactive data visualization library for Python", location: nil, category: "Plotting"),
        PackageInfo(name: "protobuf", version: "5.29.6", summary: nil, location: nil, category: "Utility"),
        PackageInfo(name: "psutil", version: "5.9.8", summary: "Cross-platform lib for process and system monitoring in Python.", location: nil, category: "Utility"),
        PackageInfo(name: "pyarrow", version: "15.0.2", summary: "Python library for Apache Arrow (iOS arm64 cross-compiled)", location: nil, category: "Data"),
        PackageInfo(name: "pycairo", version: "1.29.0", summary: "Python interface to the Cairo 2D graphics library", location: nil, category: "Animation"),
        PackageInfo(name: "pycparser", version: "2.22", summary: "C parser in Python", location: nil, category: "Utility"),
        PackageInfo(name: "pydeck", version: "0.9.2", summary: "Widget for deck.gl maps", location: nil, category: "Utility"),
        PackageInfo(name: "pydub", version: "0.25.1", summary: "Manipulate audio with an simple and easy high level interface", location: nil, category: "Media"),
        PackageInfo(name: "Pygments", version: "2.18.0", summary: "Pygments is a syntax highlighting package written in Python.", location: nil, category: "Utility"),
        PackageInfo(name: "pyparsing", version: "3.3.2", summary: "pyparsing - Classes and methods to define and execute parsing grammars", location: nil, category: "Plotting"),
        PackageInfo(name: "pyproj", version: "3.6.1", summary: "Python interface to PROJ (cartographic projections + coordinate transformations, iOS arm64)", location: nil, category: "Geo"),
        PackageInfo(name: "pyshp", version: "3.0.8", summary: "Pure Python read/write support for ESRI Shapefile format", location: nil, category: "Geo"),
        PackageInfo(name: "pywebview", version: "5.4.0", summary: "CodeBench shim: routes pywebview windows into the in-app preview pane via file IPC", location: nil, category: "Utility"),
        PackageInfo(name: "PyYAML", version: "6.0.3", summary: "YAML parser and emitter for Python", location: nil, category: "Data"),
        PackageInfo(name: "qrcode", version: "8.2", summary: "QR Code image generator", location: nil, category: "Utility"),
        PackageInfo(name: "RapidFuzz", version: "3.14.5", summary: "rapid fuzzy string matching", location: nil, category: "Performance"),
        PackageInfo(name: "referencing", version: "0.36.2", summary: "JSON Referencing + Schema Resolution", location: nil, category: "Data"),
        PackageInfo(name: "regex", version: "2024.11.6", summary: "Alternative regular expression module, to replace re.", location: nil, category: "Data"),
        PackageInfo(name: "requests", version: "2.33.1", summary: "Python HTTP for Humans.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "retrying", version: "1.4.2", summary: "Retrying", location: nil, category: "Utility"),
        PackageInfo(name: "rich", version: "13.7.0", summary: "Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal", location: nil, category: "Utility"),
        PackageInfo(name: "rpds-py", version: "0.22.3", summary: "Python bindings to the Rust 'rpds' persistent data-structure library", location: nil, category: "Data"),
        PackageInfo(name: "safetensors", version: "0.4.5", summary: nil, location: nil, category: "ML / AI"),
        PackageInfo(name: "schedule", version: "1.2.2", summary: "Job scheduling for humans.", location: nil, category: "Utility"),
        PackageInfo(name: "scikit-learn", version: "1.8.0", summary: "Machine learning algorithms in Python", location: nil, category: "ML / AI"),
        PackageInfo(name: "scipy", version: "1.15.0", summary: "Fundamental algorithms for scientific computing in Python", location: nil, category: "Scientific"),
        PackageInfo(name: "screeninfo", version: "0.8.1", summary: "Fetch location and size of physical screens.", location: nil, category: "Utility"),
        PackageInfo(name: "setuptools", version: "82.0.1", summary: "Most extensible Python build backend with support for C/C++ extension modules", location: nil, category: "Utility"),
        PackageInfo(name: "shapely", version: "2.0.6", summary: "Manipulation and analysis of geometric objects (iOS arm64 cross-compiled)", location: nil, category: "Geo"),
        PackageInfo(name: "skia-pathops", version: "0.9.2", summary: "Python bindings for the Skia path-operations library", location: nil, category: "Animation"),
        PackageInfo(name: "smmap", version: "5.0.3", summary: "A pure Python implementation of a sliding window memory map manager", location: nil, category: "Utility"),
        PackageInfo(name: "soupsieve", version: "2.8", summary: "A modern CSS selector implementation for Beautiful Soup.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "srt", version: "3.5.3", summary: "A tiny library for parsing, modifying, and composing SRT files.", location: nil, category: "Utility"),
        PackageInfo(name: "statsmodels", version: "0.14.4", summary: "Statistical computations and models for Python (iOS arm64 cross-compiled)", location: nil, category: "Utility"),
        PackageInfo(name: "streamlit", version: "1.50.0", summary: "A faster way to build and share data apps", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "svgelements", version: "1.9.6", summary: "Svg Elements Parsing", location: nil, category: "Animation"),
        PackageInfo(name: "sympy", version: "1.14.0", summary: "Computer algebra system (CAS) in Python", location: nil, category: "Scientific"),
        PackageInfo(name: "tenacity", version: "9.1.2", summary: "Retry code until it succeeds", location: nil, category: "Utility"),
        PackageInfo(name: "textual", version: "0.89.1", summary: "Textual TUI framework (trimmed bundle for iOS)", location: nil, category: "Utility"),
        PackageInfo(name: "tinycss2", version: "1.4.0", summary: "A tiny CSS parser", location: nil, category: "Utility"),
        PackageInfo(name: "tinydb", version: "4.8.2", summary: "TinyDB is a tiny, document oriented database optimized for your happiness :)", location: nil, category: "Utility"),
        PackageInfo(name: "tokenizers", version: "0.19.1", summary: nil, location: nil, category: "ML / AI"),
        PackageInfo(name: "toml", version: "0.10.2", summary: "Python Library for Tom's Obvious, Minimal Language", location: nil, category: "Utility"),
        PackageInfo(name: "torch", version: "2.1.0", summary: "Tensors and Dynamic neural networks in Python with strong GPU acceleration", location: nil, category: "ML / AI"),
        PackageInfo(name: "tornado", version: "6.5.5", summary: "Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "tqdm", version: "4.67.3", summary: "Fast, Extensible Progress Meter", location: nil, category: "Utility"),
        PackageInfo(name: "transformers", version: "4.41.2", summary: "State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow", location: nil, category: "ML / AI"),
        PackageInfo(name: "tropycal", version: "1.4", summary: "Package for retrieving and analyzing tropical cyclone data", location: nil, category: "Utility"),
        PackageInfo(name: "typing-extensions", version: "4.15.0", summary: "Backported and Experimental Type Hints for Python 3.9+", location: nil, category: "Utility"),
        PackageInfo(name: "uncertainties", version: "3.2.3", summary: "calculations with values with uncertainties, error propagation", location: nil, category: "Utility"),
        PackageInfo(name: "urllib3", version: "2.6.3", summary: "HTTP library with thread-safe connection pooling, file post, and more.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "uvloop", version: "0.22.1", summary: "Fast implementation of asyncio event loop on top of libuv", location: nil, category: "Performance"),
        PackageInfo(name: "watchdog", version: "4.0.0", summary: "Filesystem events monitoring", location: nil, category: "Utility"),
        PackageInfo(name: "wcwidth", version: "0.7.0", summary: "Measures the displayed width of unicode strings in a terminal", location: nil, category: "Utility"),
        PackageInfo(name: "webencodings", version: "0.5.1", summary: "Character encoding aliases for legacy web content", location: nil, category: "Utility"),
        PackageInfo(name: "Werkzeug", version: "3.1.8", summary: "The comprehensive WSGI web application library.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "wheel", version: "0.46.3", summary: "Command line tool for manipulating wheel files", location: nil, category: "Utility"),
        PackageInfo(name: "xarray", version: "2024.7.0", summary: "N-D labeled arrays and datasets in Python", location: nil, category: "Utility"),
        PackageInfo(name: "xxhash", version: "3.7.0", summary: "Python binding for xxHash", location: nil, category: "Performance"),
        PackageInfo(name: "zipp", version: "3.23.1", summary: "Backport of pathlib-compatible object wrapper for zip files", location: nil, category: "Utility"),
    ]

    /// Distinct categories in display order (by descending count).
    static let categories: [String] = {
        var seen = Set<String>(); var order: [String] = []
        for p in all where !seen.contains(p.category ?? "") {
            seen.insert(p.category ?? ""); order.append(p.category ?? "")
        }
        return order
    }()
}
