// BundledPackages.swift — GENERATED by scripts/gen-bundled-packages.py.
// Do not edit by hand. Regenerate after changing the python-ios-lib pin.
//
// Lists ONLY the distributions whose code is actually bundled in
// ManimStudio.app (importable top-level ∩ dist metadata) — not every
// *.dist-info under python-metadata (those include CodeBench-only
// packages whose metadata ships but whose code does not).
//
// Baked so the Packages tab is instant (no Python / importlib.metadata).

import Foundation

enum BundledPackages {
    /// 60 distributions bundled at build time.
    static let all: [PackageInfo] = [
        PackageInfo(name: "attrs", version: "24.2.0", summary: "Classes Without Boilerplate", location: nil, category: "Data"),
        PackageInfo(name: "audioop-lts", version: "0.2.1", summary: "audioop standard-library replacement for Python 3.13+.", location: nil, category: "Media"),
        PackageInfo(name: "av", version: "17.0.1", summary: "PyAV — Python bindings for FFmpeg", location: nil, category: "Media"),
        PackageInfo(name: "bs4", version: "0.0.2", summary: "Dummy package for Beautiful Soup (beautifulsoup4)", location: nil, category: "Utility"),
        PackageInfo(name: "cairo-metal", version: "0.1.0", summary: "Experimental Metal GPU backend for cairo (pycairo drop-in).", location: nil, category: "Animation"),
        PackageInfo(name: "certifi", version: "2026.2.25", summary: "Python package for providing Mozilla's CA Bundle.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "charset-normalizer", version: "3.4.7", summary: "The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "click", version: "8.1.7", summary: "Composable command line interface toolkit", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "cloup", version: "3.0.5", summary: "Adds features to Click: option groups, constraints, subcommand sections and help themes.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "cycler", version: "0.12.1", summary: "Composable style cycles", location: nil, category: "Plotting"),
        PackageInfo(name: "decorator", version: "5.3.1", summary: "Decorators for Humans", location: nil, category: "Utility"),
        PackageInfo(name: "filelock", version: "3.28.0", summary: "A platform independent file lock.", location: nil, category: "Data"),
        PackageInfo(name: "fonttools", version: "4.60.2", summary: "Font tooling; glyph-outline extraction powering Text() on iOS.", location: nil, category: "Plotting"),
        PackageInfo(name: "fsspec", version: "2026.3.0", summary: "File-system specification", location: nil, category: "Data"),
        PackageInfo(name: "idna", version: "3.11", summary: "Internationalized Domain Names in Applications (IDNA)", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "isosurfaces", version: "0.1.2", summary: "Construct isolines/isosurfaces over a 2D/3D scalar field defined by a function (not a uniform grid)", location: nil, category: "Animation"),
        PackageInfo(name: "Jinja2", version: "3.1.6", summary: "A very fast and expressive template engine.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "jsonschema", version: "4.26.0", summary: "An implementation of JSON Schema validation for Python", location: nil, category: "Data"),
        PackageInfo(name: "jsonschema-specifications", version: "2024.10.1", summary: "JSON Schema meta-schemas and vocabularies", location: nil, category: "Data"),
        PackageInfo(name: "manim", version: "0.19.0", summary: "Animation engine for explanatory math videos.", location: nil, category: "Animation"),
        PackageInfo(name: "manimpango", version: "0.6.1", summary: "Bindings for Pango (text layout) for use by manim", location: nil, category: "Animation"),
        PackageInfo(name: "mapbox-earcut", version: "1.0.3", summary: "Python bindings for the mapbox/earcut polygon-triangulation library", location: nil, category: "Animation"),
        PackageInfo(name: "markdown-it-py", version: "3.0.0", summary: "Markdown parser, used by rich for console rendering.", location: nil, category: "Utility"),
        PackageInfo(name: "MarkupSafe", version: "3.0.3", summary: "Safely add untrusted strings to HTML/XML markup.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "matplotlib", version: "3.9.0", summary: "Python plotting package", location: nil, category: "Plotting"),
        PackageInfo(name: "mdurl", version: "0.1.2", summary: "Markdown URL utilities", location: nil, category: "Utility"),
        PackageInfo(name: "moderngl", version: "5.12.0", summary: "ModernGL: High performance rendering for Python 3", location: nil, category: "Animation"),
        PackageInfo(name: "moderngl-window", version: "2.4.6", summary: "A cross-platform helper library for ModernGL / GLFW / SDL2 windows", location: nil, category: "Animation"),
        PackageInfo(name: "mpmath", version: "1.4.1", summary: "Python library for arbitrary-precision floating-point arithmetic", location: nil, category: "Scientific"),
        PackageInfo(name: "narwhals", version: "1.16.0", summary: "Extremely lightweight compatibility layer between dataframe libraries", location: nil, category: "Plotting"),
        PackageInfo(name: "networkx", version: "3.6.1", summary: "Python package for creating and manipulating graphs and networks", location: nil, category: "Scientific"),
        PackageInfo(name: "numpy", version: "2.3.5.post1", summary: "Fundamental package for array computing in Python", location: nil, category: "Scientific"),
        PackageInfo(name: "offlinai_latex", version: "1.0.1", summary: "On-device LaTeX → SVG bridge (busytex) for MathTex/Tex.", location: nil, category: "Utility"),
        PackageInfo(name: "packaging", version: "26.0", summary: "Core utilities for Python packages", location: nil, category: "Utility"),
        PackageInfo(name: "pillow", version: "11.0.0", summary: "Python Imaging Library (Fork)", location: nil, category: "Media"),
        PackageInfo(name: "plotly", version: "6.6.0", summary: "An open-source interactive data visualization library for Python", location: nil, category: "Plotting"),
        PackageInfo(name: "psutil", version: "5.9.8", summary: "Cross-platform lib for process and system monitoring in Python.", location: nil, category: "Utility"),
        PackageInfo(name: "pycairo", version: "1.29.0", summary: "Python bindings for the cairo 2D graphics library.", location: nil, category: "Animation"),
        PackageInfo(name: "pycparser", version: "2.22", summary: "C parser in Python", location: nil, category: "Utility"),
        PackageInfo(name: "pydub", version: "0.25.1", summary: "Manipulate audio with an simple and easy high level interface", location: nil, category: "Media"),
        PackageInfo(name: "Pygments", version: "2.18.0", summary: "Pygments is a syntax highlighting package written in Python.", location: nil, category: "Utility"),
        PackageInfo(name: "PyYAML", version: "6.0.3", summary: "YAML parser and emitter for Python", location: nil, category: "Data"),
        PackageInfo(name: "referencing", version: "0.36.2", summary: "JSON Referencing + Schema Resolution", location: nil, category: "Data"),
        PackageInfo(name: "regex", version: "2024.11.6", summary: "Alternative regular expression module, to replace re.", location: nil, category: "Data"),
        PackageInfo(name: "requests", version: "2.33.1", summary: "Python HTTP for Humans.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "rich", version: "13.7.0", summary: "Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal", location: nil, category: "Utility"),
        PackageInfo(name: "rpds-py", version: "0.22.3", summary: "Persistent data structures (Rust), used by jsonschema/referencing.", location: nil, category: "Data"),
        PackageInfo(name: "scikit-learn", version: "1.8.0", summary: "Machine-learning library (clustering, decomposition, …).", location: nil, category: "Scientific"),
        PackageInfo(name: "scipy", version: "1.15.0", summary: "Fundamental algorithms for scientific computing in Python", location: nil, category: "Scientific"),
        PackageInfo(name: "screeninfo", version: "0.8.1", summary: "Fetch location and size of physical screens.", location: nil, category: "Utility"),
        PackageInfo(name: "skia-pathops", version: "0.9.2", summary: "Boolean ops on Bézier paths via Skia (Union/Difference/…).", location: nil, category: "Animation"),
        PackageInfo(name: "soupsieve", version: "2.8", summary: "A modern CSS selector implementation for Beautiful Soup.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "srt", version: "3.5.3", summary: "SubRip subtitle (.srt) parser/composer; manim subtitle export.", location: nil, category: "Utility"),
        PackageInfo(name: "svgelements", version: "1.9.6", summary: "Svg Elements Parsing", location: nil, category: "Animation"),
        PackageInfo(name: "sympy", version: "1.14.0", summary: "Computer algebra system (CAS) in Python", location: nil, category: "Scientific"),
        PackageInfo(name: "tornado", version: "6.5.5", summary: "Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "tqdm", version: "4.67.3", summary: "Fast, Extensible Progress Meter", location: nil, category: "Utility"),
        PackageInfo(name: "typing-extensions", version: "4.15.0", summary: "Backported / experimental typing primitives.", location: nil, category: "Utility"),
        PackageInfo(name: "urllib3", version: "2.6.3", summary: "HTTP library with thread-safe connection pooling, file post, and more.", location: nil, category: "Web / HTTP"),
        PackageInfo(name: "watchdog", version: "4.0.0", summary: "Filesystem events monitoring", location: nil, category: "Utility"),
    ]

    /// Distinct categories in first-seen order.
    static let categories: [String] = {
        var seen = Set<String>(); var order: [String] = []
        for p in all where !seen.contains(p.category ?? "") {
            seen.insert(p.category ?? ""); order.append(p.category ?? "")
        }
        return order
    }()
}
