#!/usr/bin/env python3
"""Regenerate ManimStudio/ManimStudio/BundledPackages.swift from the
built app's python-metadata/*.dist-info.

The Packages tab reads this baked list instead of booting Python at
runtime (importlib.metadata took 2-5 s and janked the tab). The bundled
set is fixed per build, so regenerate this after changing the
python-ios-lib SwiftPM pin.

Usage:
    # 1. Build the app once (Debug, device) so python-metadata is populated:
    #    xcodebuild -project ManimStudio/ManimStudio.xcodeproj -scheme ManimStudio \
    #               -sdk iphoneos -configuration Debug CODE_SIGNING_ALLOWED=NO build
    # 2. Point this at the built .app (or its python-metadata dir):
    python3 scripts/gen-bundled-packages.py <path-to-ManimStudio.app-or-python-metadata>
"""
import os, glob, json, sys

CATEGORIES = {
    "Animation": {"manim", "manimpango", "pycairo", "cairo", "svgelements",
                  "skia-pathops", "pathops", "mapbox-earcut", "mapbox_earcut",
                  "isosurfaces", "moderngl", "moderngl-window", "moderngl_window",
                  "cairo-metal"},
    "ML / AI": {"torch", "transformers", "tokenizers", "safetensors",
                "huggingface-hub", "accelerate", "peft", "scikit-learn", "sklearn"},
    "Scientific": {"numpy", "scipy", "sympy", "mpmath", "networkx", "numexpr",
                   "bottleneck"},
    "Plotting": {"matplotlib", "plotly", "altair", "narwhals", "contourpy",
                 "cycler", "kiwisolver", "pyparsing", "fonttools"},
    "Media": {"pillow", "pil", "av", "pydub", "audioop-lts"},
    "Web / HTTP": {"requests", "urllib3", "certifi", "idna", "charset-normalizer",
                   "beautifulsoup4", "soupsieve", "flask", "werkzeug", "jinja2",
                   "markupsafe", "blinker", "itsdangerous", "click", "cloup",
                   "dash", "tornado", "streamlit", "plotly-resampler"},
    "Geo": {"cartopy", "shapely", "pyproj", "pyshp"},
    "Performance": {"orjson", "uvloop", "ciso8601", "xxhash", "rapidfuzz",
                    "levenshtein"},
    "Data": {"jsonschema", "jsonschema-specifications", "referencing", "rpds-py",
             "attrs", "attr", "pyyaml", "fsspec", "filelock", "regex", "pyarrow"},
}


def categorize(name):
    n = name.lower()
    for cat, names in CATEGORIES.items():
        if n in names:
            return cat
    return "Utility"


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    base = sys.argv[1]
    if not base.endswith("python-metadata"):
        cand = os.path.join(base, "python-metadata")
        if os.path.isdir(cand):
            base = cand
    pkgs = {}
    for di in sorted(glob.glob(os.path.join(base, "*.dist-info"))):
        meta = os.path.join(di, "METADATA")
        if not os.path.exists(meta):
            continue
        name = ver = summary = ""
        with open(meta, encoding="utf-8", errors="replace") as f:
            for line in f:
                if line.startswith("Name:") and not name:
                    name = line.split(":", 1)[1].strip()
                elif line.startswith("Version:") and not ver:
                    ver = line.split(":", 1)[1].strip()
                elif line.startswith("Summary:") and not summary:
                    s = line.split(":", 1)[1].strip()
                    summary = "" if s.upper() == "UNKNOWN" else s
                if name and ver and summary:
                    break
        if not (name and ver):
            continue
        key = name.lower()
        if key in pkgs:
            try:
                from packaging.version import Version
                if Version(ver) <= Version(pkgs[key]["version"]):
                    continue
            except Exception:
                continue
        if len(summary) > 150:
            summary = summary[:147].rstrip() + "…"
        pkgs[key] = {"name": name, "version": ver, "summary": summary,
                     "category": categorize(name)}
    out = sorted(pkgs.values(), key=lambda p: p["name"].lower())

    def esc(s):
        return (s or "").replace("\\", "\\\\").replace('"', '\\"')

    L = ["// BundledPackages.swift — GENERATED by scripts/gen-bundled-packages.py.",
         "// Do not edit by hand. Regenerate after changing the python-ios-lib pin.",
         "//",
         "// The bundled Python package set is fixed per app build, so the Packages",
         "// tab reads this baked list instead of booting Python + importlib.metadata",
         "// (which took 2-5 s and janked the tab).",
         "",
         "import Foundation",
         "",
         "enum BundledPackages {",
         f"    /// {len(out)} packages bundled at build time.",
         "    static let all: [PackageInfo] = ["]
    for p in out:
        s = f'"{esc(p["summary"])}"' if p["summary"] else "nil"
        L.append(f'        PackageInfo(name: "{esc(p["name"])}", '
                 f'version: "{esc(p["version"])}", summary: {s}, '
                 f'location: nil, category: "{esc(p["category"])}"),')
    L += ["    ]",
          "",
          "    /// Distinct categories in first-seen order.",
          "    static let categories: [String] = {",
          "        var seen = Set<String>(); var order: [String] = []",
          "        for p in all where !seen.contains(p.category ?? \"\") {",
          "            seen.insert(p.category ?? \"\"); order.append(p.category ?? \"\")",
          "        }",
          "        return order",
          "    }()",
          "}",
          ""]
    dst = os.path.join(os.path.dirname(__file__), "..",
                       "ManimStudio", "ManimStudio", "BundledPackages.swift")
    dst = os.path.abspath(dst)
    with open(dst, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {dst} ({len(out)} packages)")


if __name__ == "__main__":
    main()
